
#############################
##配置数据源信息
#############################
spring:
  datasource: #数据源相关配置
    type: com.zaxxer.hikari.HikariDataSource #数据源类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://rm-bp11dymee5j50r794do.mysql.rds.aliyuncs.com:3306/foodie?useUnicode=true&charactorEncoding=utf-8&autoReconnect=true
    username: rds_gshs_2020115
    password: rds_gshs_2020115
    hikari:
      connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒） 默认30秒。超时报SQLException异常
      minimum-idle: 5 #最小连接数
      maximum-pool-size: 20 #最大连接数
      auto-commit: true #自动提交
      idle-timeout: 600000 #连接超时的最大时长（毫秒） 默认10分钟。超时则被释放。
      pool-name: FataSourceHikariCP #连接池名字
      max-lifetime: 1800000 #连接的生命日常（毫秒）。默认30分钟。超时则被释放（retired）
      connection-test-query: SELECT 1
#######################
##mybatis配置
#######################
mybatis:
  type-aliases-package: com.hlkj.pojo
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088